### ISSUE TITLE
Add terrascan tool to the container image

### ISSUE THREAD

**Issue by Srinirap** [zenika-open-source/terraform-aws-cli#58]

**Comment by bgauduch** [comment]
Hello @Srinirap and thanks for opening this issue !

I believe that instead of adding Terrascan you would be better of building your own container image on top of this one 😉
You can achieve this using  the `FROM zenika/terraform-aws-cli:TAG` Containerfile argument.

I do not think adding every tools in the Terraform galaxy to this container image is a good practice, as it would go again the ["lightweight" philosophy](https://github.com/zenika-open-source/terraform-aws-cli#-motivation) !

**Comment by bgauduch** [comment]
Closing this issue without answer.
