### ISSUE TITLE
How do I install curl?

### ISSUE THREAD

**Issue by AndrewCharlesHay** [zenika-open-source/terraform-aws-cli#87]
The package manager seems to lack permissions and I've tried a lot of different things

**Comment by zedtux** [comment]
In the case you're not specifying the `root` user when running this image, you're running [as `nonroot` user](https://github.com/zenika-open-source/terraform-aws-cli/blob/master/Dockerfile#L65) so that you don't have rights to install packages (which is expected).

Either you're running this image with `docker` or `docker compose`, you can use the `--user` flag to request accessing your container with the `root` user.

**Comment by bgauduch** [comment]
Hello @AndrewCharlesHay 👋 

As @zedtux correctly pointed out, this container image is not intended to be run as root by default.

It uses a "nonroot" user (as seen [here](https://github.com/zenika-open-source/terraform-aws-cli/blob/master/Dockerfile#L66)) that you should be able to override if required at container runtime, depending on the Container Runtime your are using.

I'm closing this issue if you don't mind 😉

**Comment by AndrewCharlesHay** [comment]
Thanks!
